import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#d6e3fb",
        "primary-container": "#0056d2",
        "surface-container": "#eceef1",
        "inverse-surface": "#2d3133",
        "secondary-fixed-dim": "#bac7de",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e0e3e6",
        "outline-variant": "#c3c6d6",
        "on-secondary-container": "#586579",
        "surface-bright": "#f7f9fc",
        "tertiary-fixed-dim": "#ffb4ac",
        "inverse-on-surface": "#eff1f4",
        surface: "#f7f9fc",
        outline: "#737785",
        secondary: "#525f73",
        "surface-variant": "#e0e3e6",
        "inverse-primary": "#b2c5ff",
        "on-tertiary-fixed": "#410002",
        "on-primary-fixed-variant": "#0040a1",
        "on-secondary-fixed": "#0f1c2d",
        "on-error": "#ffffff",
        "tertiary-container": "#c00015",
        "on-background": "#191c1e",
        "on-primary-container": "#ccd8ff",
        "surface-container-low": "#f2f4f7",
        "on-surface-variant": "#424654",
        "primary-fixed-dim": "#b2c5ff",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#3b485a",
        primary: "#0040a1",
        "tertiary-fixed": "#ffdad6",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary-container": "#ffcdc7",
        "surface-container-high": "#e6e8eb",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001847",
        background: "#f7f9fc",
        "on-secondary": "#ffffff",
        tertiary: "#93000d",
        "primary-fixed": "#dae2ff",
        "surface-tint": "#0056d2",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#93000d",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadd",
        "secondary-fixed": "#d6e3fb",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "Manrope", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
