; PlatformIO Project Configuration File - ASTRAEA 2 mode sensor/camera
; Usage:
;   pio run -e sensor -t upload  (mode sensor IR+HC-SR04, queue cm)
;   pio run -e camera -t upload  (mode camera YOLO, tanpa cm)
;   pio run -e esp32cam -t upload (ESP32-CAM stream)

[platformio]
default_envs = sensor

[env:sensor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
	bblanchon/ArduinoJson@^7.2.2
	knolleary/PubSubClient@^2.8
build_flags =
	-DMQTT_MAX_PACKET_SIZE=2048
	-DMQTT_SOCKET_TIMEOUT=15
src_dir = src_sensor

[env:camera]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
	bblanchon/ArduinoJson@^7.2.2
	knolleary/PubSubClient@^2.8
build_flags =
	-DMQTT_MAX_PACKET_SIZE=2048
	-DMQTT_SOCKET_TIMEOUT=15
src_dir = src_camera

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
upload_speed = 921600
lib_deps =
	bblanchon/ArduinoJson@^7.2.2
