; ASTRAEA Controller v2 — 1x ESP32 DevKit (traffic light + IR/HC-SR04)
; Buka folder ini di VSCode + PlatformIO.
[env:astraea-controller]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^6.21.5
