; ASTRAEA-CAM v1 — ESP32-CAM AI-Thinker (1 firmware untuk 3 kamera)
; Buka folder ini di VSCode + PlatformIO. Flash ke 3 board satu per satu,
; identitas tiap kamera (ID + token) diisi via SoftAP, BUKAN via kode.
[env:astraea-cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
lib_deps =
  bblanchon/ArduinoJson@^6.21.5
  gilmaimon/ArduinoWebsockets@^0.5.4
